// <auto-generated />
namespace Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedDateofBirth3IndividualInts1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDateofBirth3IndividualInts1));
        
        string IMigrationMetadata.Id
        {
            get { return "201604110109389_addedDateofBirth3IndividualInts1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
